name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npx yarn install
      - name: Start
        run: npx yarn start
